// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjKMiq6ucLQBSlamqkbfKKnS2bxZe1d8o',
    appId: '1:636657363748:android:a915f3a3a5a907d0d721b1',
    messagingSenderId: '636657363748',
    projectId: 'sentimentanalysis-7ba59',
    storageBucket: 'sentimentanalysis-7ba59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56sVjdCi8zU9Hj2Zjtw2Q7ydiO398G0o',
    appId: '1:636657363748:ios:b81a844da36a62d0d721b1',
    messagingSenderId: '636657363748',
    projectId: 'sentimentanalysis-7ba59',
    storageBucket: 'sentimentanalysis-7ba59.firebasestorage.app',
    iosBundleId: 'com.example.almari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9rhtqpU3ZydripFZntWfb0kYEqerhYPw',
    appId: '1:636657363748:web:400e2c7a6edcf30ad721b1',
    messagingSenderId: '636657363748',
    projectId: 'sentimentanalysis-7ba59',
    authDomain: 'sentimentanalysis-7ba59.firebaseapp.com',
    storageBucket: 'sentimentanalysis-7ba59.firebasestorage.app',
    measurementId: 'G-F65DRNBHJV',
  );
}
